### ISSUE TITLE
Potential lead on the \0\0\0\0 constant in de/player

### ISSUE THREAD

**Issue by ZetaTwo** [happyleavesaoc/aoc-mgz#106]
In the Player struct of the DE header there is a field that's currently set to a constant of 4 null bytes: https://github.com/happyleavesaoc/aoc-mgz/blob/deea5c428c2b8c205843c49776b0d78ff51e3261/mgz/header/de.py#L38

I found a replay in my collection where this is instead 4 0xff, alternatively if we interpret this as an int32 it is "-1" instead of "0" which it seems to be in the overwhelming majority of cases. The player in question is the third player which is an AI opponent.

I'm attaching the replay file.

Here is the output from "mgz dump thisfile.aoe2record":

```
Traceback (most recent call last):
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 1042, in _parse
    obj.append(self.subcon._parse(stream, context._, path))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 1936, in _parse
    raise ConstError("expected %r but parsed %r" % (self.value, obj))
construct.core.ConstError: expected b'\x00\x00\x00\x00' but parsed b'\xff\xff\xff\xff'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 1050, in _parse
    raise RangeError("expected %d to %d, found %d" % (min, max, len(obj)))
construct.core.RangeError: expected 3 to 3, found 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zetatwo/.local/bin/mgz", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/mgz/cli.py", line 231, in main
    loop.run_until_complete(run(get_args()))
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/mgz/cli.py", line 190, in run
    dump_rec(rec)
  File "/home/zetatwo/.local/lib/python3.12/site-packages/mgz/cli.py", line 78, in dump_rec
    mgz.header.parse_stream(handle)
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/mgz/util.py", line 58, in _parse
    return self.subcon._parse(new_stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 357, in _parse
    return self.subcon.parse(data, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 158, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 1594, in _parse
    obj = self.cases.get(key, self.default)._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zetatwo/.local/lib/python3.12/site-packages/construct/core.py", line 2788, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.RangeError: expected 3 to 3, found 2
    (parsing) -> de -> de -> players
```

specifically, we notice the
```
construct.core.ConstError: expected b'\x00\x00\x00\x00' but parsed b'\xff\xff\xff\xff'
```

[MP Replay v101.102.46236.0 @2024.05.03 214225 (1).aoe2record.zip](https://github.com/user-attachments/files/17156975/MP.Replay.v101.102.46236.0.%402024.05.03.214225.1.aoe2record.zip)

**Comment by happyleavesaoc** [comment]
1) Does the DE header parse correctly if you replace `Const` with `Int32`?
2) Can you reproduce this behavior with another rec w/ AI?

**Comment by ZetaTwo** [comment]
1. If I replace if with a Int32sl it works perfectly fine:
```
PYTHONPATH=. python3 mgz/cli.py info MP\ Replay\ v101.102.46236.0\ @2024.05.03\ 214225\ \(1\).aoe2record 
/home/zetatwo/Projects/aoe2-replay-parsing/aoc-mgz/mgz/cli.py:230: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
INFO:mgz.summary:using model summary
-------------
/home/zetatwo/Projects/aoe2-replay-parsing/aoc-mgz/mgz/cli.py:43: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  ['Played', datetime.utcfromtimestamp(summary.get_played()) if summary.get_played() else None],
Path        /mnt/hgfs/Share/AoE2-research/replays/MP Replay v101.102.46236.0 @2024.05.03 214225 (1).aoe2record
Duration    00:01:12
Played      2024-05-03 18:42:25
Completed   True
Restored    False
Postgame    False
Version     Version.DE (VER 9.4, 62.0, 5, 111772)
Dataset     Definitive Edition None
File Hash   a5966087b59d02fa12c48317f2880e51010897f7
Match Hash  0aa9b38219e16385485803fe80e52f808f40f50a
Encoding    utf-8
Language    en
Device      0
Map         Golden Swamp (953364866, None)
```

2. I have found 19 multiplayer replays in my collection that have this and a bunch of single player ones as well. I will go through them and try to figure out if I find a pattern. I can also upload them but they are ~100mb together.

**Comment by ZetaTwo** [comment]
Even though the meaning is not known I think we can close this once the PR is merged.
