### ISSUE TITLE
RuntimeError: could not get map data: could not detect encoding

### ISSUE THREAD

**Issue by denniske** [happyleavesaoc/aoc-mgz#115]
Hi, I want to find out how to draw a aoe2 map with different terrains. So I created a custom scenario with all the different terrains. But the recording cannot be parsed by aoc mgz. I get the following error:

```
Traceback (most recent call last):
  File "/Users/dennis/Projects/aoe2companion-mgz/env/lib/python3.13/site-packages/mgz/model/__init__.py", line 112, in parse_match
        map_data, encoding, language = get_map_data(
                                       ~~~~~~~~~~~~^
        map_id,
        ^^^^^^^
    ...<6 lines>...
        de_seed=data['lobby']['seed']
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/dennis/Projects/aoe2companion-mgz/env/lib/python3.13/site-packages/mgz/common/map.py", line 191, in get_map_data
    encoding, language, name = extract_from_instructions(instructions)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/dennis/Projects/aoe2companion-mgz/env/lib/python3.13/site-packages/mgz/common/map.py", line 99, in extract_from_instructions
    raise ValueError('could not detect encoding')
ValueError: could not detect encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dennis/Projects/aoe2companion-mgz/src/process.py", line 48, in <module>
    match = parse_match(h)
  File "/Users/dennis/Projects/aoe2companion-mgz/env/lib/python3.13/site-packages/mgz/model/__init__.py", line 123, in parse_match
    raise RuntimeError(f"could not get map data: {e}")
RuntimeError: could not get map data: could not detect encoding
```

[mini1.aoe2record.zip](https://github.com/user-attachments/files/18221200/mini1.aoe2record.zip)

**Comment by happyleavesaoc** [comment]
`aoc-mgz` is not great at parsing scenarios, especially if there is AI or something like that. It will work best on recorded games from multiplayer random maps.

**Comment by denniske** [comment]
It is just an empty map where I painted different terrains in the upper left side. Do you think I can fix it without a lot of knowledge on the scenario format?

[allterrain.zip](https://github.com/user-attachments/files/18222866/allterrain.zip)

**Comment by happyleavesaoc** [comment]
I do not know how complicated it would be. Could be single unexpected a single byte or something a lot trickier.

**Comment by denniske** [comment]
I just found out that I can still access the map tiles with `print(data['map'])` even when the remaining data cannot be parsed. I got all the terrain ids and will close this issue.
