### ISSUE TITLE
How to install and use it?

### ISSUE THREAD

**Issue by Defozo** [happyleavesaoc/aoc-mgz#16]
When I run `sudo python3.6 setup.py install`
I get:
```
running install
Checking .pth file support in /usr/local/lib/python3.6/dist-packages/
/usr/bin/python3.6 -E -c pass
TEST PASSED: /usr/local/lib/python3.6/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing mgz.egg-info/PKG-INFO
writing dependency_links to mgz.egg-info/dependency_links.txt
writing entry points to mgz.egg-info/entry_points.txt
writing requirements to mgz.egg-info/requires.txt
writing top-level names to mgz.egg-info/top_level.txt
reading manifest file 'mgz.egg-info/SOURCES.txt'
writing manifest file 'mgz.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying mgz.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mgz.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mgz.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mgz.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mgz.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mgz.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    'Programming Language :: Python :: 3',
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by happyleavesaoc** [comment]
1) I'd recommend you use a virtual environment. (`python3.6 -m venv <your_env_name>; source <your_env_name/bin/activate>`.
2a) If you're installing from a `git clone`: from the root directory of the clone: `pip install -e .`
2b) If you're installing from pypi, `pip install mgz`

**Comment by Defozo** [comment]
Thank you!
