### ISSUE TITLE
Parsing latest patch saved .aoe2record files

### ISSUE THREAD

**Issue by thepalbi** [happyleavesaoc/aoc-mgz#22]
Hi @happyleavesaoc !

First of all, great work and thanks for developing this recorded games parses.

I'm trying to parse some recorded games from yesterday (latest patch applied), and I'm getting the following error when running the `Summary(data)` example in the README:
```
Traceback (most recent call last):
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mgz/cli.py", line 285, in <module>
    main()
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mgz/cli.py", line 281, in main
    loop.run_until_complete(run(get_args()))
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mgz/cli.py", line 223, in run
    print_info(rec)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mgz/cli.py", line 75, in print_info
    header = mgz.header.parse_stream(handle)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/mgz/util.py", line 55, in _parse
    return self.subcon._parse(new_stream, context, path)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 357, in _parse
    return self.subcon.parse(data, context)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 158, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/Users/thepalbi/.pyenv/versions/3.8.1/lib/python3.8/site-packages/construct/core.py", line 1036, in _parse
    raise RangeError("unsane min %s and max %s" % (min, max))
construct.core.RangeError: unsane min -1 and max -1
```

Any clue what's the cause? Maybe I can help.

**Comment by happyleavesaoc** [comment]
Latest patch is supported in https://github.com/happyleavesaoc/aoc-mgz/commit/f5ebbde43c664950810ecd25b42d61a5bf7828bc. You'll have to clone the repo to get it, no pip release yet.
