### ISSUE TITLE
expected b'`\n' but parsed b'\x89\xda' - (parsing) -> de -> de -> ai_files

### ISSUE THREAD

**Issue by denniske** [happyleavesaoc/aoc-mgz#45]
Following error occured:

match_id: 64686137
profile_id: 1670341

```python
Traceback (most recent call last):
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 1936, in _parse
    raise ConstError("expected %r but parsed %r" % (self.value, obj))
construct.core.ConstError: expected b'`\n' but parsed b'\x89\xda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 1042, in _parse
    obj.append(self.subcon._parse(stream, context._, path))
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 2788, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.ConstError: expected b'`\n' but parsed b'\x89\xda'
    (parsing) -> de -> de -> ai_files -> name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 1050, in _parse
    raise RangeError("expected %d to %d, found %d" % (min, max, len(obj)))
construct.core.RangeError: expected 4205749679821946880 to 4205749679821946880, found 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/pypy-latest-linux64/site-packages/mgz/summary/__init__.py", line 72, in __init__
    self._header = mgz.header.parse_stream(self._handle)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/mgz/util.py", line 57, in _parse
    return self.subcon._parse(new_stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 357, in _parse
    return self.subcon.parse(data, context)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 158, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 1594, in _parse
    obj = self.cases.get(key, self.default)._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 2784, in _parse
    return self.subcon._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
  File "/root/pypy-latest-linux64/site-packages/construct/core.py", line 2788, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.RangeError: expected 4205749679821946880 to 4205749679821946880, found 0
    (parsing) -> de -> de -> ai_files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/process.py", line 42, in <module>
    summary = mgz.summary.Summary(handle, None)
  File "/root/pypy-latest-linux64/site-packages/mgz/summary/__init__.py", line 84, in __init__
    raise RuntimeError("invalid mgz file: {}".format(e))
RuntimeError: invalid mgz file: expected 4205749679821946880 to 4205749679821946880, found 0
    (parsing) -> de -> de -> ai_files
```

**Comment by denniske** [comment]
[AgeIIDE_Replay_64686137.zip](https://github.com/happyleavesaoc/aoc-mgz/files/5899446/AgeIIDE_Replay_64686137.zip)
