### ISSUE TITLE
SyntaxError: can't use starred expression here

### ISSUE THREAD

**Issue by jchmb** [happyleavesaoc/aoc-mgz#57]
With Python 3.9 this throws a syntax error. It seems to work fine with Python 3.6, however.

```python
Traceback (most recent call last):
  File "(removed)\test.py", line 1, in <module>
    from mgz.model import parse_match
  File "(removed)\LocalCache\local-packages\Python39\site-packages\mgz\model\__init__.py", line 8, in <module>
    from mgz.fast.header import parse
  File "(removed)\LocalCache\local-packages\Python39\site-packages\mgz\fast\header.py", line 108
    type_, (*diplomacy), name_length = unpack(f'<bx{num_players}x9i5xh', header)
            ^
SyntaxError: can't use starred expression here
```

When I change the line to the version below it works with both Python versions. 

```python
type_, *diplomacy, name_length = unpack(f'<bx{num_players}x9i5xh', header)
```

**Comment by happyleavesaoc** [comment]
Fixed @ https://github.com/happyleavesaoc/aoc-mgz/pull/58
