### ISSUE TITLE
RuntimeError: invalid mgz file: expected 3 to 3, found 2

### ISSUE THREAD

**Issue by Namek** [happyleavesaoc/aoc-mgz#70]
```
Traceback (most recent call last):
  File "C:\dev\ant_league\backend\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\dev\ant_league\backend\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "C:\dev\ant_league\backend\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\middleware\sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\dev\ant_league\backend\lib\site-packages\fastapi\routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "C:\dev\ant_league\backend\lib\site-packages\fastapi\routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\dev\ant_league\backend\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Users\Namek\AppData\Local\Programs\Python\Python38\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\dev\ant_league\backend\src\website.py", line 127, in post_match
    match_info = utils.get_match_info(file.file)
  File "C:\dev\ant_league\backend\src\utils.py", line 44, in get_match_info
    s = Summary(data)
  File "c:\dev\ant_league\backend\mgz\mgz\summary\__init__.py", line 85, in __init__
    raise RuntimeError("invalid mgz file: {}".format(e))
RuntimeError: invalid mgz file: expected 3 to 3, found 2
    (parsing) -> initial
```

[MP_Replay_v101.101.53347.0_2021.09.16_214614_1.zip](https://github.com/happyleavesaoc/aoc-mgz/files/7185211/MP_Replay_v101.101.53347.0_2021.09.16_214614_1.zip)

**Comment by happyleavesaoc** [comment]
Hi, `git clone` the repository to get the latest code. I tested your rec and your example and received no errors on the latest commit.
