### ISSUE TITLE
Can't run summary example

### ISSUE THREAD

**Issue by catorda** [happyleavesaoc/aoc-mgz#8]
I'm new to python, so I'm probably missing something, but I've run the setup.py install / build, and I'm getting this error message that it can't find the AOC module
```
Traceback (most recent call last):
  File "summary.py", line 1, in <module>
    from mgz.summary import Summary
  File "/mnt/c/Users/Trina/Development/aoc-mgz/mgz/summary/__init__.py", line 24, in <module>
    from mgz.summary.extract import get_extracted_data
  File "/mnt/c/Users/Trina/Development/aoc-mgz/mgz/summary/extract.py", line 6, in <module>
    from mgz.playback import Client, Source
  File "/mnt/c/Users/Trina/Development/aoc-mgz/mgz/playback.py", line 
16, in <module>
    from AOC import ConfigMessage
ModuleNotFoundError: No module named 'AOC' 
```
I tried searching to see how to install this AOC module but I can't find it.

**Comment by happyleavesaoc** [comment]
Hi, that module (which enables playback/extraction) is not yet public. I pushed a commit that will prevent the `import` from failing. Practically, this just means you can't call `Summary`'s `extract()` method. Everything else should work.

**Comment by happyleavesaoc** [comment]
Closing this since it should be fixed but I haven't had any confirmation for awhile. Please re-open if it still does not work!

**Comment by vinzeebreak** [comment]
Hi!

I have the last version and I got the problem.

```
mgz play data/recs/rec.20200402-202657.mgz
```

gives:

```
Traceback (most recent call last):
  File "/home/vinzeebreak/.virtualenvs/aoeii37/bin/mgz", line 8, in <module>
    sys.exit(main())
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/mgz/cli.py", line 281, in main
    loop.run_until_complete(run(get_args()))
  File "/home/linuxbrew/.linuxbrew/Cellar/python/3.7.6_1/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/mgz/cli.py", line 217, in run
    await play_rec(args.playback.split(',')[0], rec)
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/mgz/cli.py", line 47, in play_rec
    from mgz.playback import Client, progress_bar
  File "/home/vinzeebreak/.virtualenvs/aoeii37/lib/python3.7/site-packages/mgz/playback.py", line 15, in <module>
    from AOC import ConfigMessage
ModuleNotFoundError: No module named 'AOC'
```
