### ISSUE TITLE
Full summary isn't working

### ISSUE THREAD

**Issue by M1ngXU** [happyleavesaoc/aoc-mgz#96]
```
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\mgz\summary\full.py", line 75, in __init__
    self._header = mgz.header.parse_stream(self._handle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 295, in _parse
    return self.subcon._parse(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\mgz\util.py", line 73, in _parse
    return self.subcon._parse(new_stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 357, in _parse
    return self.subcon.parse(data, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 158, in parse
    return self.parse_stream(BytesIO(data), context, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 171, in parse_stream
    return self._parse(stream, context2, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 867, in _parse
    subobj = sc._parse(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\construct\core.py", line 2788, in _parse
    raise e.__class__("%s\n    %s" % (e, path))
construct.core.RangeError: expected 7 to 7, found 1
    (parsing) -> initial
```
works with the fast parser

**Comment by happyleavesaoc** [comment]
Please supply the recorded game. Thx!

**Comment by M1ngXU** [comment]
this seems to be a problem with the new patch in general? should i still send the savegame?

**Comment by happyleavesaoc** [comment]
Confirmed this issue. Working to fix.

**Comment by M1ngXU** [comment]
great, it works now :)
